name: rsoi-logger
image: dockerhub.rigellab.ru/rsoi/logger
port: 80
waitDb: rsoi-postgres
env:
  DB_URL: rsoi-postgres/logger
  DB_USER: logger
  DB_PASSWORD: postgres
  KAFKA: rsoi-kafka:9092
  JWKS: http://rsoi-auth/well-known
