name: rsoi-auth
image: dockerhub.rigellab.ru/rsoi/auth
port: 80
waitDb: rsoi-postgres
env:
  DB_URL: rsoi-postgres/auth
  DB_USER: auth
  DB_PASSWORD: postgres
  JWT_LIFETIME: 2592000
  KAFKA: rsoi-kafka:9092
  KEYS_PATH: /var/auth-keys
  OAUTH_REDICRECT: "http://example.com/callback"

secretEnv:
  - YANDEX_CLIENT_ID
  - YANDEX_CLIENT_SECRET
  - GOOGLE_CLIENT_ID
  - GOOGLE_CLIENT_SECRET

pvc:
  enabled: true
  size: 32Ki
  name: auth-volume
  mountPath: var/auth-keys
  storageClass: keep
