name: rsoi-postgres
image: postgres
tag: 17
port: 5432
servicePort: 5432

env:
  PGUSER: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

dbInit: true

pvc:
  enabled: true
  size: 2Gi
  name: mysql-volume
  mountPath: var/lib/postgresql/data