name: rsoi-reservation
image: dockerhub.rigellab.ru/rsoi/reservation
port: 8070

waitDb: rsoi-postgres

env:
  DB_HOST: rsoi-postgres
  DB_NAME: reservation
  DB_USER: reservation
  DB_PASSWORD: postgres
  KAFKA: rsoi-kafka:9092
  JWKS: rsoi-auth:8030/well-known
