name: rsoi-loyalty
image: dockerhub.rigellab.ru/rsoi/loyalty
port: 8050
waitDb: rsoi-postgres
env:
  DB_HOST: rsoi-postgres
  DB_NAME: loyalty
  DB_USER: loyalty
  DB_PASSWORD: postgres
  KAFKA: rsoi-kafka:9092
