CREATE DATABASE person;
CREATE DATABASE reservation;
CREATE DATABASE loyalty;
CREATE DATABASE payment;

GRANT ALL PRIVILEGES ON DATABASE person TO program;
GRANT ALL PRIVILEGES ON DATABASE reservation TO program;
GRANT ALL PRIVILEGES ON DATABASE loyalty TO program;
GRANT ALL PRIVILEGES ON DATABASE payment TO program;